export const LANGS = ['en', 'id'] as const;
export type Lang = (typeof LANGS)[number];

export const dict = {
  en: {
    appName: 'BBB CRM',
    tagline: 'A simple CRM for small business owners.',

    // Auth
    login: 'Log in',
    signup: 'Sign up',
    logout: 'Log out',
    email: 'Email',
    password: 'Password',
    businessName: 'Business name',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    loginCta: 'Log in',
    signupCta: 'Create account',
    checkEmail: 'Check your email to confirm your account, then log in.',
    forgotPassword: 'Forgot password?',
    forgotPasswordTitle: 'Reset your password',
    forgotPasswordHint: "Enter your email and we'll send you a link to set a new password.",
    sendResetLink: 'Send reset link',
    resetLinkSent: 'Check your email for the reset link.',
    resetPasswordTitle: 'Set a new password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    passwordsDoNotMatch: 'Passwords do not match.',
    passwordUpdated: 'Password updated. You can now log in.',
    backToLogin: '← Back to log in',
    verifyingLink: 'Verifying the link…',
    invalidResetLink: 'This link is invalid or has expired. Please request a new one.',

    // Captcha
    captchaRequired: 'Please complete the verification.',

    // Auth errors (friendly versions of Supabase server messages)
    errEmailRateLimit: "You've requested too many emails in a short time. Wait an hour, or try a different email address.",
    errBadCredentials: 'Wrong email or password.',
    errEmailNotConfirmed: 'You need to confirm your email first — check your inbox.',
    errCaptcha: 'Verification failed. Please try the captcha again.',
    errWeakPassword: 'That password is too short or too easy. Use at least 6 characters.',
    errUserExists: 'An account with that email already exists. Try logging in instead.',
    errLinkExpired: 'This link has expired. Request a new one.',

    // Inline help
    help: 'Help',
    gotIt: 'Got it',

    helpAdsTitle: 'What is the Ads tab?',
    helpAdsBody:
      "Track every marketing campaign you run (Instagram ad, Facebook ad, flyer drop, referral push) and see exactly how much each one brings in.\n\nFor each campaign you note: name, source, how much you spent, when it ran. Then when a customer signs up, you pick which campaign brought them in (the 'How did they find you?' field). The Ads tab uses that to show you:\n\n• Customers acquired per campaign\n• Revenue generated by those customers\n• CAC (cost per acquisition)\n• ROAS (return on ad spend)\n\nIf CAC stays below the average customer value, the ad is profitable.",

    helpCacTitle: 'CAC — Cost per Acquisition',
    helpCacBody:
      "How much you spent on ads to get ONE customer.\n\nFormula: total ad spend ÷ customers acquired from that ad\n\nExample: if you spent Rp 500.000 on a Facebook ad and 5 customers came in from it, CAC = Rp 100.000 per customer.\n\nLower is better. Compare CAC to how much each customer spends on average (lifetime value). If CAC < lifetime value → the ad is paying off.",

    helpRoasTitle: 'ROAS — Return on Ad Spend',
    helpRoasBody:
      'How many times you earned back your ad spend.\n\nFormula: revenue from customers acquired ÷ ad spend\n\nExample: spent Rp 500.000 on an ad, got 5 customers who together spent Rp 2.500.000 → ROAS = 5×, meaning you made back 5 times what you spent.\n\nGenerally:\n• ROAS < 1× = losing money on the ad\n• ROAS 1× — 2× = breaking even or barely profitable\n• ROAS 3× or higher = healthy',

    helpIncomeTitle: 'Total income from customers',
    helpIncomeBody:
      'Sum of every amount you logged across every interaction with every customer. This is your total recorded revenue from the CRM.\n\nTo grow this number, add an amount whenever you log a visit, sale, or service for a customer.',

    helpDormantTitle: 'Quiet for 30+ days',
    helpDormantBody:
      "Customers you haven't logged any interaction with in the last 30 days. They're at risk of forgetting about you.\n\nTip: send them a short personal WhatsApp (the 💚 button on the customer detail page does this in one tap).",

    helpPipelineTitle: 'Pipeline statuses',
    helpPipelineBody:
      "Where each customer is in their journey with you:\n\n• Cold — barely engaged, hasn't bought yet\n• Warm — interested, you're talking with them\n• Hot — about to buy / very engaged\n• Active — has actually bought (your loyal customer)\n• Pause — was active but now quiet / on hold\n\nTap any number on the pipeline strip to see those customers.\n\nChange a customer's status by tapping the status pill at the top of their detail page.",

    helpLtvTitle: 'Lifetime value (LTV)',
    helpLtvBody:
      "Total amount this customer has paid you across every interaction you've logged.\n\nGrows as you log more sales / visits with an amount filled in.\n\nUseful for spotting your VIPs (highest LTV) and for sanity-checking ad campaigns — if a customer from a Facebook ad ends up with LTV that's 5× your CAC, that ad is doing great.",

    // Nav
    home: 'Home',
    customers: 'Customers',
    addCustomer: 'Add customer',
    add: 'Add',

    // Dashboard
    totalCustomers: 'Total customers',
    dormant30: 'Quiet for 30+ days',
    birthdaysToday: "Today's birthdays",
    welcome: 'Welcome',
    quickActions: 'Quick actions',

    // Customer list
    searchPlaceholder: 'Search by name or phone',
    noCustomersYet: "No customers yet. Tap '+' to add your first one.",
    noResults: 'No matches.',

    // Customer form
    name: 'Name',
    firstName: 'First name',
    lastName: 'Last name',
    phone: 'Phone (WhatsApp)',
    birthday: 'Birthday',
    tags: 'Tags',
    notes: 'Notes',
    save: 'Save',
    cancel: 'Cancel',
    saving: 'Saving…',
    required: 'Required',
    newTagPlaceholder: 'New tag…',
    removeTag: 'Remove',
    noTagsYet: 'No tags yet — add your first.',
    exportCsv: 'Export CSV',
    importCsv: 'Import CSV',
    importCustomers: 'Import customers',
    importHint: 'Upload a CSV from a spreadsheet or another CRM.',
    chooseFile: 'Choose your file',
    pickCsv: 'Tap to choose a CSV file',
    matchColumns: 'Match your columns',
    matchColumnsHint: "We've auto-matched what we can — adjust if anything is off.",
    skipColumn: 'Skip',
    previewImport: 'Preview ({n} of {total} rows ready to import)',
    more: 'more',
    importing: 'Importing…',
    importDuplicateWarning: 'Duplicates are not auto-merged. Clean your file first if needed.',
    csvEmpty: 'That file looks empty.',
    importedN: '✓ Imported {n} customers',
    downloadTemplate: 'Download template',
    attributeAll: 'Where did these customers come from?',
    attributeAllHint: 'Pick a campaign to attribute ALL imported customers to. Leave on "Per row" if your file has a Campaign column.',
    attributePerRow: 'Per row (read from CSV)',
    campaignResolveStatus: '{matched} of {total} rows match a campaign by name.',

    // Edit + tag management
    edit: 'Edit',
    editCustomer: 'Edit customer',
    delete: 'Delete',
    manageTags: 'Manage tags',
    manageTagsHint: 'Renaming a tag updates it on every customer who uses it.',
    confirmDeleteTag: 'Delete the tag "{name}"? Customers will keep the label but the catalog row goes away.',
    dangerZone: 'Danger zone',
    dangerZoneHint: 'Deleting a customer also removes their whole interaction history. This cannot be undone.',

    // Ads / CAC
    ads: 'Ads',
    newCampaign: 'New campaign',
    editCampaign: 'Edit campaign',
    deleteCampaign: 'Delete campaign',
    confirmDeleteCampaign: 'Delete this campaign? Customers attributed to it will lose their attribution.',
    campaignName: 'Campaign name',
    source: 'Source',
    spend: 'Spend',
    spendIdr: 'Spend (IDR)',
    startedAt: 'Started',
    endedAt: 'Ended',
    noCampaignsYet: 'No campaigns yet — track your first ad to see your CAC.',
    noCampaignsHintForCustomer: 'Create a campaign on the Ads tab first.',
    campaignNone: 'Not from an ad',
    howFoundYou: 'How did they find you?',
    totalSpend: 'Total ad spend',
    customersFromAds: 'Customers from ads',
    avgCac: 'Average CAC',
    overallRoas: 'Overall ROAS',
    customersShort: 'Customers',
    revenueShort: 'Revenue',
    sourceInstagram: 'Instagram',
    sourceFacebook: 'Facebook',
    sourceTiktok: 'TikTok',
    sourceGoogle: 'Google',
    sourceWhatsapp: 'WhatsApp',
    sourceReferral: 'Referral',
    sourceFlyer: 'Flyer',
    sourceWalkIn: 'Walk-in',
    sourceOther: 'Other',

    // Customer detail
    timeline: 'History',
    noInteractionsYet: 'No history yet.',
    logInteraction: 'Log a visit',
    kind: 'What happened',
    visitKind: 'Visit',
    callKind: 'Call',
    saleKind: 'Sale',
    messageKind: 'Message',
    otherKind: 'Other',
    amount: 'Amount (optional)',
    occurredAt: 'When',
    today: 'today',
    yesterday: 'yesterday',
    daysAgo: '{n} days ago',
    openWhatsApp: 'WhatsApp',
    deleteCustomer: 'Delete customer',
    confirmDelete: 'Delete this customer and all their history?',

    // Status / pipeline
    status: 'Status',
    statusCold: 'Cold',
    statusWarm: 'Warm',
    statusHot: 'Hot',
    statusDealDone: 'Active',
    statusPaused: 'Paused',
    pipeline: 'Pipeline',
    allStatuses: 'All',
    changeStatus: 'Change status',

    // Lifetime value
    lifetimeValue: 'Lifetime value',
    ltvShort: 'LTV',
    totalCustomersLtv: 'Total income from customers',

    // Misc
    loading: 'Loading…',
    error: 'Something went wrong.',
  },
  id: {
    appName: 'BBB CRM',
    tagline: 'CRM sederhana untuk pemilik usaha kecil.',

    login: 'Masuk',
    signup: 'Daftar',
    logout: 'Keluar',
    email: 'Email',
    password: 'Kata sandi',
    businessName: 'Nama usaha',
    noAccount: 'Belum punya akun?',
    haveAccount: 'Sudah punya akun?',
    loginCta: 'Masuk',
    signupCta: 'Buat akun',
    checkEmail: 'Cek email kamu untuk konfirmasi akun, lalu masuk.',
    forgotPassword: 'Lupa kata sandi?',
    forgotPasswordTitle: 'Reset kata sandi',
    forgotPasswordHint: 'Masukin email kamu, nanti kami kirim link buat bikin kata sandi baru.',
    sendResetLink: 'Kirim link reset',
    resetLinkSent: 'Cek email kamu untuk link reset.',
    resetPasswordTitle: 'Bikin kata sandi baru',
    newPassword: 'Kata sandi baru',
    confirmPassword: 'Konfirmasi kata sandi baru',
    passwordsDoNotMatch: 'Kata sandi tidak cocok.',
    passwordUpdated: 'Kata sandi sudah diperbarui. Silakan masuk.',
    backToLogin: '← Kembali ke halaman masuk',
    verifyingLink: 'Memverifikasi link…',
    invalidResetLink: 'Link ini tidak valid atau sudah kedaluwarsa. Silakan minta link baru.',

    // Captcha
    captchaRequired: 'Mohon selesaikan verifikasi.',

    // Auth errors (friendly versions of Supabase server messages)
    errEmailRateLimit: 'Kamu udah minta terlalu banyak email dalam waktu singkat. Tunggu sejam, atau pakai email lain.',
    errBadCredentials: 'Email atau kata sandi salah.',
    errEmailNotConfirmed: 'Kamu perlu konfirmasi email kamu dulu — cek inbox.',
    errCaptcha: 'Verifikasi gagal. Coba captcha-nya lagi.',
    errWeakPassword: 'Kata sandi terlalu pendek atau gampang. Pakai minimal 6 karakter.',
    errUserExists: 'Akun dengan email ini udah ada. Coba masuk aja.',
    errLinkExpired: 'Link ini udah kedaluwarsa. Minta link baru.',

    // Inline help
    help: 'Bantuan',
    gotIt: 'Mengerti',

    helpAdsTitle: 'Apa itu tab Iklan?',
    helpAdsBody:
      'Catat tiap kampanye marketing yang kamu jalanin (iklan IG, FB, sebar brosur, referral) dan lihat berapa banyak yang masuk dari masing-masing.\n\nTiap kampanye kamu catat: nama, sumber, berapa biaya yang dikeluarkan, kapan jalan. Pas customer baru daftar, kamu pilih kampanye mana yang bawa dia (kolom "Dari mana mereka tau kamu?"). Tab Iklan otomatis ngitung:\n\n• Berapa customer yang dapet dari tiap kampanye\n• Pendapatan dari customer itu\n• CAC (biaya per customer)\n• ROAS (perbandingan pendapatan vs biaya iklan)\n\nKalo CAC lebih kecil dari rata-rata belanja customer, iklan kamu untung.',

    helpCacTitle: 'CAC — Biaya per Customer',
    helpCacBody:
      'Berapa biaya iklan yang kamu keluarin buat dapet SATU customer.\n\nRumus: total biaya iklan ÷ jumlah customer dari iklan itu\n\nContoh: kamu spend Rp 500.000 di iklan Facebook dan dapat 5 customer → CAC = Rp 100.000 per customer.\n\nMakin kecil makin bagus. Bandingin sama rata-rata belanja customer (lifetime value). Kalo CAC < lifetime value → iklan kamu profit.',

    helpRoasTitle: 'ROAS — Return on Ad Spend',
    helpRoasBody:
      'Berapa kali lipat balik modal dari iklan kamu.\n\nRumus: pendapatan dari customer iklan ÷ biaya iklan\n\nContoh: spend Rp 500.000, dapat 5 customer total belanja Rp 2.500.000 → ROAS = 5×, artinya kamu balik 5 kali lipat.\n\nUmumnya:\n• ROAS < 1× = rugi\n• ROAS 1× — 2× = pas-pasan\n• ROAS 3× ke atas = sehat',

    helpIncomeTitle: 'Total pendapatan dari customer',
    helpIncomeBody:
      'Jumlah semua nominal yang kamu catat di setiap interaksi sama customer. Ini total pendapatan kamu dari CRM.\n\nBiar naik, isi kolom nominal tiap kali catat kunjungan, penjualan, atau servis.',

    helpDormantTitle: 'Sudah 30+ hari nggak kontak',
    helpDormantBody:
      'Customer yang belum kamu catat interaksinya selama 30 hari terakhir. Berisiko lupa sama kamu.\n\nTips: kirim chat WhatsApp pribadi yang singkat (tombol 💚 di halaman detail customer langsung buka WhatsApp).',

    helpPipelineTitle: 'Status pipeline',
    helpPipelineBody:
      'Posisi tiap customer di perjalanan mereka sama kamu:\n\n• Dingin — masih dingin, belum beli\n• Hangat — tertarik, lagi ngobrol sama kamu\n• Panas — siap beli / sangat tertarik\n• Aktif — udah beli (customer setia kamu)\n• Pause — pernah aktif tapi sekarang diem / off\n\nTap angka di strip pipeline buat lihat customer-nya.\n\nUbah status customer dengan tap pill status di atas halaman detail mereka.',

    helpLtvTitle: 'Lifetime value (LTV)',
    helpLtvBody:
      'Total nominal yang customer ini udah bayar ke kamu di semua interaksi yang tercatat.\n\nBertambah tiap kamu catat sale/visit dengan nominal terisi.\n\nBerguna buat lihat VIP kamu (LTV tertinggi) dan cek kampanye iklan — kalo customer dari iklan FB punya LTV 5× CAC, iklan itu mantap.',

    home: 'Beranda',
    customers: 'Customer',
    addCustomer: 'Tambah customer',
    add: 'Tambah',

    totalCustomers: 'Total customer',
    dormant30: 'Sudah 30+ hari nggak kontak',
    birthdaysToday: 'Ulang tahun hari ini',
    welcome: 'Halo',
    quickActions: 'Aksi cepat',

    searchPlaceholder: 'Cari nama atau nomor',
    noCustomersYet: "Belum ada customer. Tap '+' untuk tambah yang pertama.",
    noResults: 'Tidak ada hasil.',

    name: 'Nama',
    firstName: 'Nama depan',
    lastName: 'Nama belakang',
    phone: 'Nomor (WhatsApp)',
    birthday: 'Tanggal lahir',
    tags: 'Tag',
    notes: 'Catatan',
    save: 'Simpan',
    cancel: 'Batal',
    saving: 'Menyimpan…',
    required: 'Wajib diisi',
    newTagPlaceholder: 'Tag baru…',
    removeTag: 'Hapus',
    noTagsYet: 'Belum ada tag — tambahkan yang pertama.',
    exportCsv: 'Export CSV',
    importCsv: 'Import CSV',
    importCustomers: 'Import customer',
    importHint: 'Upload CSV dari spreadsheet atau CRM lain.',
    chooseFile: 'Pilih file',
    pickCsv: 'Tap untuk pilih file CSV',
    matchColumns: 'Cocokin kolom',
    matchColumnsHint: 'Kami sudah cocokin sebisanya — ubah kalau ada yang salah.',
    skipColumn: 'Skip',
    previewImport: 'Preview ({n} dari {total} baris siap diimport)',
    more: 'lagi',
    importing: 'Importing…',
    importDuplicateWarning: 'Data duplikat tidak digabung otomatis. Bersihkan file dulu kalau perlu.',
    csvEmpty: 'File-nya kelihatan kosong.',
    importedN: '✓ {n} customer berhasil diimport',
    downloadTemplate: 'Download template',
    attributeAll: 'Customer ini dari mana?',
    attributeAllHint: 'Pilih kampanye buat ngatribusi SEMUA customer yang diimport. Tetap di "Per baris" kalau file kamu udah punya kolom Campaign.',
    attributePerRow: 'Per baris (baca dari CSV)',
    campaignResolveStatus: '{matched} dari {total} baris cocok ke kampanye berdasarkan nama.',

    // Edit + tag management
    edit: 'Edit',
    editCustomer: 'Edit customer',
    delete: 'Hapus',
    manageTags: 'Atur tag',
    manageTagsHint: 'Ubah nama tag bakal kepake ke semua customer yang punya tag itu.',
    confirmDeleteTag: 'Hapus tag "{name}"? Customer tetep punya label-nya, tapi tag-nya hilang dari katalog.',
    dangerZone: 'Zona berbahaya',
    dangerZoneHint: 'Hapus customer juga ngehapus seluruh riwayatnya. Nggak bisa dibalikin.',

    // Ads / CAC
    ads: 'Iklan',
    newCampaign: 'Kampanye baru',
    editCampaign: 'Edit kampanye',
    deleteCampaign: 'Hapus kampanye',
    confirmDeleteCampaign: 'Hapus kampanye ini? Customer yang terhubung ke kampanye ini bakal kehilangan atribusinya.',
    campaignName: 'Nama kampanye',
    source: 'Sumber',
    spend: 'Biaya iklan',
    spendIdr: 'Biaya (IDR)',
    startedAt: 'Mulai',
    endedAt: 'Selesai',
    noCampaignsYet: 'Belum ada kampanye — catat iklan pertama kamu buat lihat CAC.',
    noCampaignsHintForCustomer: 'Buat kampanye dulu di tab Iklan.',
    campaignNone: 'Bukan dari iklan',
    howFoundYou: 'Dari mana mereka tau kamu?',
    totalSpend: 'Total biaya iklan',
    customersFromAds: 'Customer dari iklan',
    avgCac: 'CAC rata-rata',
    overallRoas: 'ROAS keseluruhan',
    customersShort: 'Customer',
    revenueShort: 'Pendapatan',
    sourceInstagram: 'Instagram',
    sourceFacebook: 'Facebook',
    sourceTiktok: 'TikTok',
    sourceGoogle: 'Google',
    sourceWhatsapp: 'WhatsApp',
    sourceReferral: 'Referral',
    sourceFlyer: 'Brosur',
    sourceWalkIn: 'Walk-in',
    sourceOther: 'Lainnya',

    timeline: 'Riwayat',
    noInteractionsYet: 'Belum ada riwayat.',
    logInteraction: 'Catat kunjungan',
    kind: 'Kegiatan',
    visitKind: 'Kunjungan',
    callKind: 'Telepon',
    saleKind: 'Penjualan',
    messageKind: 'Chat',
    otherKind: 'Lainnya',
    amount: 'Nominal (opsional)',
    occurredAt: 'Kapan',
    today: 'hari ini',
    yesterday: 'kemarin',
    daysAgo: '{n} hari lalu',
    openWhatsApp: 'WhatsApp',
    deleteCustomer: 'Hapus customer',
    confirmDelete: 'Hapus customer ini beserta seluruh riwayatnya?',

    // Status / pipeline
    status: 'Status',
    statusCold: 'Dingin',
    statusWarm: 'Hangat',
    statusHot: 'Panas',
    statusDealDone: 'Aktif',
    statusPaused: 'Pause',
    pipeline: 'Pipeline',
    allStatuses: 'Semua',
    changeStatus: 'Ubah status',

    // Lifetime value
    lifetimeValue: 'Total belanja',
    ltvShort: 'LTV',
    totalCustomersLtv: 'Total pendapatan dari customer',

    loading: 'Memuat…',
    error: 'Terjadi kesalahan.',
  },
} as const;

export type DictKey = keyof typeof dict.en;
